### ISSUE TITLE
Make possible to run gppi convertation as a separate step.

### ISSUE THREAD

**Issue by karbyshevds** [odahu/odahu-trainer#25]
**Is your feature request related to a problem? Please describe.**
GPPI packaging is part or ODAHU toolchain, it makes impossible to deploy models in other formats without training

**Describe the solution you'd like**
The idea is to make packaging a separate step to allow call it as from toolchain to provide current behaviour as from odahu-flow-ctl to convert existing models to ODAHU compatible format.

**Describe alternatives you've considered**
Alternative is to run any model you want to deploy via full ODAHU toolchain which can be very expensive in terms of time and machine power.

**Additional context**

**Comment by vlad-tokarev** [comment]
please add the optional flag --zip
If flag is passed then we need to zip odahu model the same way as we do it in Cluster
@keshamin

**Comment by BPylypenko** [comment]
OK, works.
But when `--zip` flag is active, the gppi converter creates both, the folder with gppi model and tar archive.

The example of odahuflow.project.yaml:
```
binaries:
  conda_path: odahuflow_model/conda.yaml
  dependencies: conda
  type: python
model:
  entrypoint: entrypoint
  name: 'test-gppi-converter '
  version: '1.0'
  workDir: odahuflow_model
odahuflowVersion: '1.0'
toolchain:
  name: mlflow
  version: 1.13.1
```
I don't what It means "odahuflowVersion: '1.0'"? Could you, please, say it's version of what?
And, I suppose, that values for name, version, and others which are passed through parameters should be trimmed. Because, for example, I mistakenly passed the model name with the following space and it was transfered the same into project.yaml.
@keshamin, @vlad-tokarev
